# IMPORTING LIBRARIES

In [1]:
#Loading
import pandas as pd
import numpy as np

#Data Visualisation
import seaborn as sns
import matplotlib.pyplot as plt

# TO READ  TRAIN DATASET

In [2]:
df=pd.read_csv('Final_Train_Dataset.csv') 
df.head()

Unnamed: 0 experience                                    job_description  \
0           0    5-7 yrs  Exp: Minimum 5 years;Good understanding of IOC...   
1           1  10-17 yrs  He should have handled a team of atleast 5-6 d...   
2           2    5-9 yrs  Must be an effective communicator (written & s...   
3           3   7-10 yrs  7  -  10 years of overall experience in data e...   
4           4    1-3 yrs  Chartered Accountancy degree or MBA in Finance...   

                                           job_desig   job_type  \
0        Senior Exploit and Vulnerability Researcher        NaN   
1                                           Head SCM        NaN   
2  Deputy Manager - Talent Management & Leadershi...  Analytics   
3                 Associate Manager Data Engineering  Analytics   
4                            TS- GSA- Senior Analyst        NaN   

                                          key_skills               location  \
0  team skills, communication skills, analytical ...  Delhi NCR(Vikas Puri)   
1  ppc, logistics, inventory management, supply c...                Sonepat   
2  HR Analytics, Employee Engagement, Training, S...              Delhi NCR   
3  SQL, Javascript, Automation, Python, Ruby, Ana...              Bengaluru   
4  accounting, finance, cash flow, financial plan...                Gurgaon   

   salary  company_name_encoded  
0   6to10                  3687  
1  10to15                   458  
2  15to25                  4195  
3  10to15                   313  
4    3to6                  1305

In [3]:
df.shape

(19802, 9)

In [4]:
df.columns

Index(['Unnamed: 0', 'experience', 'job_description', 'job_desig', 'job_type',
       'key_skills', 'location', 'salary', 'company_name_encoded'],
      dtype='object')

In [5]:
df.nunique()

Unnamed: 0              19802
experience                129
job_description          9059
job_desig               11708
job_type                    5
key_skills              12951
location                 1504
salary                      6
company_name_encoded     5035
dtype: int64

In [6]:
df['job_type'].unique()

array([nan, 'Analytics', 'analytics', 'Analytic', 'ANALYTICS', 'analytic'],
      dtype=object)

In [7]:
df['salary'].unique()

array(['6to10', '10to15', '15to25', '3to6', '25to50', '0to3'],
      dtype=object)

# Descriptive Statistics 

In [8]:
df.describe()

Unnamed: 0  company_name_encoded
count  19802.000000          19802.000000
mean    9900.500000           2379.723866
std     5716.489351           1475.342341
min        0.000000              0.000000
25%     4950.250000           1067.000000
50%     9900.500000           2225.000000
75%    14850.750000           3621.000000
max    19801.000000           5034.000000

In [9]:
data1=df.drop(['Unnamed: 0','job_description','job_type','key_skills'], axis = 1)

# DATA PREPROCESSING

In [10]:
data1.head()

experience                                          job_desig  \
0    5-7 yrs        Senior Exploit and Vulnerability Researcher   
1  10-17 yrs                                           Head SCM   
2    5-9 yrs  Deputy Manager - Talent Management & Leadershi...   
3   7-10 yrs                 Associate Manager Data Engineering   
4    1-3 yrs                            TS- GSA- Senior Analyst   

                location  salary  company_name_encoded  
0  Delhi NCR(Vikas Puri)   6to10                  3687  
1                Sonepat  10to15                   458  
2              Delhi NCR  15to25                  4195  
3              Bengaluru  10to15                   313  
4                Gurgaon    3to6                  1305

In [11]:
data1.isna().sum()

experience              0
job_desig               0
location                0
salary                  0
company_name_encoded    0
dtype: int64

There is no missing value present in the dataset

# Feature Reduction

In [12]:
data1.drop(['job_desig'],axis=1,inplace=True)

# Splitting of train data into feature and target columns

In [13]:
X=data1.drop(['salary'],axis=1)
X.head()

experience               location  company_name_encoded
0    5-7 yrs  Delhi NCR(Vikas Puri)                  3687
1  10-17 yrs                Sonepat                   458
2    5-9 yrs              Delhi NCR                  4195
3   7-10 yrs              Bengaluru                   313
4    1-3 yrs                Gurgaon                  1305

In [14]:
y=data1['salary']

# Encoding of train dataset

In [15]:
X.columns

Index(['experience', 'location', 'company_name_encoded'], dtype='object')

# Label Encoding

In [16]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [17]:
X['experience']=lb.fit_transform(X['experience'])

In [18]:
X['location']=lb.fit_transform(X['location'])

# One Hot Encoding 

In [19]:
X.dtypes

experience              int32
location                int32
company_name_encoded    int64
dtype: object

# Splitting of X into train and test sets for modelling

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.25)

In [21]:
X_test.shape

(4951, 3)

In [22]:
X_test.columns

Index(['experience', 'location', 'company_name_encoded'], dtype='object')

# Scaling

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit_transform(X_train)

array([[ 0.17392348, -1.33536767, -0.27317231],
       [ 0.1981203 , -0.37625226, -0.27317231],
       [ 0.99661527,  1.4346323 ,  1.18843481],
       ...,
       [ 0.63366301, -0.37625226,  0.64160266],
       [ 1.11759935,  1.4346323 ,  0.84014271],
       [-1.68923144, -1.33536767,  0.50472522]])

# Logistic Regression

In [24]:
import warnings
warnings.filterwarnings('ignore')

In [25]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [26]:
y_pred1=lr.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score,recall_score

In [28]:
a1=accuracy_score(y_test,y_pred1)
f1=f1_score(y_test,y_pred1,average='micro')
r1=recall_score(y_test,y_pred1,average='micro')

In [29]:
d1={'metric':['Accuracy','F1 score','Recall score'],'values':[a1,f1,r1]}

In [30]:
pd.DataFrame(d1)

metric    values
0      Accuracy  0.315694
1      F1 score  0.315694
2  Recall score  0.315694

In [31]:
confusion_matrix(y_test,y_pred1)

array([[ 524,  236,    8,    0,    0,    0],
       [ 140, 1009,   19,    0,    1,    0],
       [ 171,  814,   30,    0,    2,    0],
       [ 107,  247,   19,    0,    2,    0],
       [ 243,  486,    9,    0,    0,    0],
       [ 117,  760,    7,    0,    0,    0]], dtype=int64)

In [32]:
#Evaluation Metric
Score1= max(0,100*accuracy_score(y_test,y_pred1))
Score1

31.56937992324783

# Decision Tree

In [33]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [34]:
y_pred2=dt.predict(X_test)

In [35]:
a2=accuracy_score(y_test,y_pred2)
f2=f1_score(y_test,y_pred2,average='micro')
r2=recall_score(y_test,y_pred2,average='micro')

In [37]:
d2={'metric':['Accuracy','F1 score','Recall score'],'values':[a2,f2,r2]}

In [38]:
pd.DataFrame(d2)

metric    values
0      Accuracy  0.358513
1      F1 score  0.358513
2  Recall score  0.358513

In [39]:
confusion_matrix(y_test,y_pred2)

array([[429,  43,  27,   3, 195,  71],
       [ 56, 437, 389,  22,  60, 205],
       [ 31, 379, 352, 142,  35,  78],
       [  4,  37, 169, 155,   6,   4],
       [223,  83,  35,   3, 241, 153],
       [ 89, 280, 149,  13, 192, 161]], dtype=int64)

In [40]:
#Evaluation Metric
Score2= max(0,100*accuracy_score(y_test,y_pred2))
Score2

35.851343162997374

# Random Forest Classifier

In [41]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [42]:
y_pred3=rf.predict(X_test)

In [43]:
a3=accuracy_score(y_test,y_pred3)
f3=f1_score(y_test,y_pred3,average='micro')
r3=recall_score(y_test,y_pred3,average='micro')

In [44]:
d3={'metric':['Accuracy','F1 score','Recall score'],'values':[a3,f3,r3]}

In [45]:
pd.DataFrame(d3)

metric    values
0      Accuracy  0.363361
1      F1 score  0.363361
2  Recall score  0.363361

In [46]:
confusion_matrix(y_test,y_pred3)

array([[455,  44,  17,   5, 171,  76],
       [ 39, 378, 413,  21,  65, 253],
       [ 24, 337, 384, 152,  23,  97],
       [  1,  24, 166, 173,   6,   5],
       [218,  71,  37,   2, 217, 193],
       [ 83, 269, 161,   9, 170, 192]], dtype=int64)

In [47]:
#Evaluation Metric
Score3= max(0,100*accuracy_score(y_test,y_pred3))
Score3

36.33609371844072

# Gradient Boosting Classifier

In [48]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(X_train,y_train)

GradientBoostingClassifier()

In [49]:
y_pred4=gb.predict(X_test)

In [50]:
a4=accuracy_score(y_test,y_pred4)
f4=f1_score(y_test,y_pred4,average='micro')
r4=recall_score(y_test,y_pred4,average='micro')

In [51]:
d4={'metric':['Accuracy','F1 score','Recall score'],'values':[a4,f4,r4]}

In [52]:
pd.DataFrame(d4)

metric    values
0      Accuracy  0.426177
1      F1 score  0.426177
2  Recall score  0.426177

In [53]:
#Evaluation Metric
Score4= max(0,100*accuracy_score(y_test,y_pred4))
Score4

42.61765299939406

From this it is clear that the best algorithm for fitting is Gradient Boosting Classifier since accuracy of this algorithm is higher compared to others.

# To predict in Test Dataset using the above algorithm

In [56]:
data=pd.read_csv('Final_Test_Dataset.csv') 
data.head()

experience                                    job_description  \
0   7-12 yrs  Professional experience in Java/J2EE based ser...   
1    0-5 yrs  We are looking for 20+ Fresher/Experienced Can...   
2    3-6 yrs  Should understand overall integration framewor...   
3    0-3 yrs                                                NaN   
4    0-5 yrs                                                NaN   

                                           job_desig job_type  \
0  IT Technology Senior Consultant/java/ J2ee/ Se...      NaN   
1  Medical Billing Process | International KPO | ...      NaN   
2           Oracle Sales Cloud Functional Consultant      NaN   
3      Looking For Freshers WHO WANT To Work WITH US      NaN   
4  Process Associate / Sr Process Associate / Tec...      NaN   

                                          key_skills  \
0  Java, J2Ee, Tomcat, JBoss, Weblogic, Oracle, E...   
1              Medical Billing, Insurance Processing   
2  Oracle Sales, Functional Consultancy, Troubles...   
3  offline, online, internet, part time, home bas...   
4  voice support, analytical skills, Process asso...   

                                            location  company_name_encoded  
0                                          Bengaluru                  2066  
1                                    Ahmedabad(Sola)                  2629  
2                                          Bengaluru                  2448  
3  Delhi NCR, Chennai, Hyderabad, Gurgaon, Luckno...                  2711  
4                                          Hyderabad                    40

In [57]:
data2=data.drop(['job_description','job_type','key_skills'], axis = 1)

In [58]:
data2.head()

experience                                          job_desig  \
0   7-12 yrs  IT Technology Senior Consultant/java/ J2ee/ Se...   
1    0-5 yrs  Medical Billing Process | International KPO | ...   
2    3-6 yrs           Oracle Sales Cloud Functional Consultant   
3    0-3 yrs      Looking For Freshers WHO WANT To Work WITH US   
4    0-5 yrs  Process Associate / Sr Process Associate / Tec...   

                                            location  company_name_encoded  
0                                          Bengaluru                  2066  
1                                    Ahmedabad(Sola)                  2629  
2                                          Bengaluru                  2448  
3  Delhi NCR, Chennai, Hyderabad, Gurgaon, Luckno...                  2711  
4                                          Hyderabad                    40

In [59]:
data2.isna().sum()

experience              0
job_desig               0
location                0
company_name_encoded    0
dtype: int64

# Feature Reduction

In [60]:
data2.drop(['job_desig'],axis=1,inplace=True)

# Encoding of train dataset

In [61]:
X.columns

Index(['experience', 'location', 'company_name_encoded'], dtype='object')

# Label Encoding

In [62]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [63]:
X['experience']=lb.fit_transform(X['experience'])

In [64]:
X['location']=lb.fit_transform(X['location'])

# One hot encoding

In [65]:
X.dtypes

experience              int64
location                int64
company_name_encoded    int64
dtype: object